Add AsteroidExplodesWithSettler testcase
poiuztrewq1/projlab_holy_oil pull request #171
Opened 2021-03-19 21:38 UTC by triszt4n

Closes #144

2021-03-19 21:47 UTC, vercibar requested changes
🤔

2021-03-19 21:47 UTC, vercibar commented on java/src/hu/holyoil/skeleton/testcases/AsteroidExplodesWithSettler.java
> +        Logger.SetEnabled(true);
👀

2021-03-19 22:05 UTC, triszt4n commented on java/src/hu/holyoil/skeleton/testcases/AsteroidExplodesWithSettler.java
> +        Logger.SetEnabled(true);
done

2021-03-19 22:20 UTC, triszt4n commented on java/src/hu/holyoil/neighbour/Asteroid.java
> +        }
Still not the best solution (just tested it in a new test case).

2021-03-19 22:20 UTC, triszt4n commented on java/src/hu/holyoil/neighbour/Asteroid.java
> +        }
I'mma keep on working on this

2021-03-19 22:29 UTC, triszt4n commented on java/src/hu/holyoil/neighbour/Asteroid.java
> +        }
Found it, needs shallow copy!

2021-03-20 11:38 UTC, vercibar approved these changes
😉

2021-03-20 11:45 UTC, merged