Play game command
poiuztrewq1/projlab_holy_oil pull request #276
Opened 2021-04-15 21:46 UTC by poiuztrewq1

- Done the play game command. If the user is in play mode and the command is not recognized, it won't exit. (first commit)
- I thought we could do something really fancy and searched for an algorithm to get the closest matching command from a list. So when somebody types `caus_sunstrom` the program will ask `Did you mean cause_sunstorm?` 

Questions:
- Do we keep this, or not really needed.
- Should the program exit on an error like `Invalid number of arguments`.

closes #260

2021-04-15 22:33 UTC, triszt4n requested changes
Love it, Levenstein's is a nice feature. 🚀 

Answers to questions:
1. Feature can stay.
2. Right now the `Handle` method returns if interpreting the command was successful, and in every case we override `isRunning` with the return value. You can introduce a new variable `isInterpreted`, and use it to store the return value in that. One more thing: the `while` cycle should consider this variable when in play mode. This way the code below can stay as is, and we need a new conditional outside the `default` case and run the conditional everytime a line is read and `isPlayMode && !isInterpreted`.

2021-04-15 22:33 UTC, triszt4n commented on java/src/hu/holyoil/controller/InputOutputController.java
> +                    }
This

2021-04-16 08:07 UTC, vercibar commented
Shouldn't this command also generate the world using GameController.StartGame()?

2021-04-16 11:19 UTC, poiuztrewq1 commented
> 
> 
> Shouldn't this command also generate the world using GameController.StartGame()?

Well, can do, but please refer to the issue of the PR:
```
The user might mistype a command, and then the program closes with an error. Maybe we should let this happen.
SOLUTION: Make a new command in InputOutputController for the user called play in that case the InputOutputController won't close the program in case of an invalid command (this should also switch off the Logger, like echo_off).
```

2021-04-18 09:22 UTC, triszt4n approved these changes
# Nice 🥇

2021-04-18 09:33 UTC, merged