gui seq diagrams
poiuztrewq1/projlab_holy_oil pull request #304
Opened 2021-04-24 17:31 UTC by vercibar

2021-04-24 19:17 UTC, triszt4n commented
All done?

2021-04-24 19:29 UTC, vercibar commented
as far as i know its done

2021-04-24 19:31 UTC, triszt4n approved these changes
I've removed unnecessary files in the commit above. One plantuml seq dia is unnecessary. Everything else is fine.

2021-04-24 19:31 UTC, triszt4n commented on uml/gui_seq_diagrams/draw.plantuml
> +@enduml
This file isn't even needed, you've already made `update_gameframe.plantuml`.

2021-04-24 19:31 UTC, triszt4n commented on uml/gui_seq_diagrams/draw.plantuml
> +@enduml
Sorry, this review should've been a request for cahnge

2021-04-24 19:35 UTC, triszt4n requested changes

2021-04-24 19:35 UTC, triszt4n commented on uml/gui_seq_diagrams/mouseclicked_environmentpanel.plantuml
> +    env -> gameFrame ++: GetPlayer()
hmm getcurrentplayer should come from turncontroller

2021-04-24 19:35 UTC, triszt4n commented on uml/gui_seq_diagrams/mouseclicked_environmentpanel.plantuml
> +    env -> gameFrame ++: GetPlayer()
merge latest commits from ref/class-rethinking plesae

2021-04-24 19:35 UTC, triszt4n commented on uml/gui_seq_diagrams/mouseclicked_environmentpanel.plantuml
> +    env -> gameFrame ++: GetPlayer()
I'm getting more and more chaotic sossry

2021-04-25 14:15 UTC, triszt4n commented
Na most magyarul: a turncontrollerből szerzik mostantól a diagramok a jelenlegi játékost. Kicsit kiegészítettem a draw game sequenciát, hogy ne sírjon a szájuk

2021-04-25 14:22 UTC, triszt4n approved these changes
# 🍭

2021-04-25 14:40 UTC, merged