Minimalistic Log panel and skip button
poiuztrewq1/projlab_holy_oil pull request #327
Opened 2021-05-04 21:31 UTC by vercibar

Closes #310

2021-05-04 21:32 UTC, vercibar commented
Merged #326 because it did not compile without it

2021-05-04 21:58 UTC, triszt4n requested changes
Gonna make a proper review in the morning I've written this review from the mobile GitHub app, and I'm already almost sleeping gbye

2021-05-04 21:58 UTC, triszt4n commented on java/src/hu/holyoil/view/panels/LogPanel.java
> +                new MouseListener() {
I guess the MouseAdapter abstract class is better than the MouseListener interface for this

2021-05-05 07:39 UTC, triszt4n commented
Na megnéztem, nem rossz, actually tetszik meg minden, de esetleg meg tudnád ezt is hozzá csinálni: https://github.com/poiuztrewq1/projlab_holy_oil/issues/328?
Jó lenne a modellnek az osztályaiból kiszedni a nem kellő loggereket (basically mindent lehet törölni), és az indentációk meg minden sequentia faszság nélkül kiírni ilyen eventeket, mint ahogy az issue-ban leírtam

2021-05-05 07:41 UTC, triszt4n commented on java/src/hu/holyoil/commandhandler/Logger.java
>          }
Igazából ez a függvény mehet a levesbe

2021-05-05 07:41 UTC, triszt4n commented on java/src/hu/holyoil/commandhandler/Logger.java
>          }
És ez is

2021-05-05 09:01 UTC, vercibar commented
Closes #328

2021-05-05 14:35 UTC, triszt4n approved these changes
# 🍪

2021-05-05 16:12 UTC, merged